POST http://127.0.0.1.8000/
Content-Type: application/json

{"username":"zack"}

###
POST http://127.0.0.1:8000/users/api/login/
Content-Type: application/json

{"username":"superadmin", "password":"superadmin"}

###
POST http://127.0.0.1:8000/campaign/api/campaigns/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjQ3NjI0LCJpYXQiOjE3Mzg2NDI4MjQsImp0aSI6Ijk5OTM3ZDA5OWJjZjQxZDBiNDI3NGE1YmY3Y2UyMGM1IiwidXNlcl9pZCI6MTN9.DEGQKKHUIdsVs16aFxJu9Jq---3UO06brEGlJf_OXoY

{
    "type": "Email",
    "text": "Welcome to our new product launch!",
    "description": "This campaign is to introduce our latest product to our users." 
}
###
GET http://127.0.0.1:8000/campaign/api/campaigns/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzU5OTI5LCJpYXQiOjE3Mzg3NTUxMjksImp0aSI6ImU0NGU0N2Y0ODNjZjRlMjNhODk5ZTA5ODBkNzEyN2VmIiwidXNlcl9pZCI6MTR9.4ShHfgqOoN_XuivTGlOwTJl3M3aS-XtOtUmRQrcBqCE
###
###
DELETE  http://127.0.0.1:8000/campaign/api/campaigns/11/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzYwMDUzLCJpYXQiOjE3Mzg3NTUyNTMsImp0aSI6Ijk2MTBmMGYxMTJmMTRlNzJhNTBhNGUxMmRhNmY0N2FlIiwidXNlcl9pZCI6MTN9.3w5B_LPOIWBDleXmCJ7-7Wh1qXwyfJJbY3ErG7Hnf2c
###
PUT http://127.0.0.1:8000/campaign/api/campaigns/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NjMxNjc5LCJpYXQiOjE3Mzc2MzEzNzksImp0aSI6IjIwNzQzODYxZWVlMzQwN2Q4YmM0YTIzZDc5NGYzNDRlIiwidXNlcl9pZCI6MTR9.rAj9dWe58odKs80buu2BvnydHbx2AO6FUAMiTs5iM_I

{
    "type": "Emaillllll",
    "text": "Welcome to our new product launch!",
    "description": "This campaign is to introduce our latest product to our users." 
}
###

###
GET http://127.0.0.1:8000/campaign/api/campaigns/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjQ3NjI0LCJpYXQiOjE3Mzg2NDI4MjQsImp0aSI6Ijk5OTM3ZDA5OWJjZjQxZDBiNDI3NGE1YmY3Y2UyMGM1IiwidXNlcl9pZCI6MTN9.DEGQKKHUIdsVs16aFxJu9Jq---3UO06brEGlJf_OXoY


###
GET http://127.0.0.1:8000/campaign/api/send_email/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzEwMTkwLCJpYXQiOjE3Mzc3MDk4OTAsImp0aSI6IjM3ZWYwOGRlMTBiYTRmMTBhNjQyMWI4ZTAzNmJmMWIyIiwidXNlcl9pZCI6MTN9.fLU51Kl7aX64oUznNFnZ42AzIOlgGsnYRXIQJx3hNn8

###
POST http://127.0.0.1:8000/campaign/api/send_email/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjQ3NjI0LCJpYXQiOjE3Mzg2NDI4MjQsImp0aSI6Ijk5OTM3ZDA5OWJjZjQxZDBiNDI3NGE1YmY3Y2UyMGM1IiwidXNlcl9pZCI6MTN9.DEGQKKHUIdsVs16aFxJu9Jq---3UO06brEGlJf_OXoY

{"campaign_id":10, "on_email":true, "send_now":true, "scheduled_time": "2025-01-29T16:06:00Z"}



########### USER API ENDPOINTS

###
POST http://127.0.0.1:8000/users/api/signup/
Content-Type: application/json

{"username":"n__jul11111", "email":"anjulkushwaha11@gmail.com", "first_name":"anjul", "last_name":"kus", "password":"123123", "practice_id": 2}

###
GET http://127.0.0.1:8000/users/api/practice/


##########MESSAGE RELATED ENDPOINTS.

###
GET http://127.0.0.1:8000/campaign/api/message/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTU0MTAwLCJpYXQiOjE3Mzc5NTM4MDAsImp0aSI6Ijc1NjhlYzM2ZmY3ODQyODBhYjBkMGZlYTM0YTVjNTJjIiwidXNlcl9pZCI6MTV9.IPOf-JkYd2C_ZRsSmpYBv6oZb-aVlCtNTn2voLCnVCE

###
PUT http://127.0.0.1:8000/campaign/api/message/10/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTU3Nzc4LCJpYXQiOjE3Mzc5NTc0NzgsImp0aSI6ImYyZWJiM2ZiZmZiNjQxOGRhMDA5YjE0ZjNhYWEzZDA1IiwidXNlcl9pZCI6MTV9.F2cvyBDB29e0rlooYs949JaLsR104ns8gBgKr6MwGp4





##### ENDPOINTS FOR SCHEDULING CAMPAIGNS

POST http://127.0.0.1:8000/campaign/api/schedule_campaign/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MjI4MjE1LCJpYXQiOjE3MzgyMjc5MTUsImp0aSI6IjMzY2RmZTI2MTNlNjQ4ZThiMWQzMWRmNjE2ZDdiY2UxIiwidXNlcl9pZCI6MTN9.uHs7D_0Te6cl3qovjkJvXGGOZ_kMymtRtL0xgYZfhR8

{
    "campaign_id":10,
    "scheduled_date":"2025-01-30 17:00:00+05:30"
}



####admin related endpoints

###
POST http://127.0.0.1:8000/users/api/login/
Content-Type: application/json

{"username":"test_admin", "password":"test123"}

###
POST http://127.0.0.1:8000/campaign/api/campaigns/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MTgwNzMzLCJpYXQiOjE3Mzg1NzU5MzMsImp0aSI6IjlhNGZiYWNhY2ZiNjQ2OTNhZmIyZDEzYmZhZmZjOGJjIiwidXNlcl9pZCI6MTN9.Q2xR8OaUVX45qelllWw33-tzPCOHYqBGC9h7fpRBMDw

{
    "type": "Email",
    "text": "checking for admin id!",
    "description": "This campaign is to introduce our latest product to our users." 
}

###
GET http://127.0.0.1:8000/campaign/api/admin/campaigns/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MTgwNzMzLCJpYXQiOjE3Mzg1NzU5MzMsImp0aSI6IjlhNGZiYWNhY2ZiNjQ2OTNhZmIyZDEzYmZhZmZjOGJjIiwidXNlcl9pZCI6MTN9.Q2xR8OaUVX45qelllWw33-tzPCOHYqBGC9h7fpRBMDw

###
PUT http://127.0.0.1:8000/campaign/api/campaigns/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MTgwNzMzLCJpYXQiOjE3Mzg1NzU5MzMsImp0aSI6IjlhNGZiYWNhY2ZiNjQ2OTNhZmIyZDEzYmZhZmZjOGJjIiwidXNlcl9pZCI6MTN9.Q2xR8OaUVX45qelllWw33-tzPCOHYqBGC9h7fpRBMDw

{
    "type": "Emaillllll149",
    "text": "checking for admin and superadmin id!",
    "description": "This campaign is to introduce our latest product to our users." 
}

###
POST http://127.0.0.1:8000/campaign/api/sa_campaigns/
Content-Type: application/json

{
    "campaign_id":10,
    "practice_ids": [2,3,4,5,6,7,8,9,10,11]
}
