# alembic/versions/xxxxxx_initial_migration.py

"""Initial migration for UserCampaign and UserCampaignSequence models"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import BigInteger, String, DateTime, ForeignKey
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'xxxxxx'  # This is auto-generated by Alembic
down_revision = None  # or the last applied migration (if any)
branch_labels = None
depends_on = None


def upgrade():
    # Create the user_campaign table
    op.create_table(
        'user_campaign',
        sa.Column('id', BigInteger, primary_key=True, autoincrement=True),
        sa.Column('type', String, nullable=False),
        sa.Column('text', String, nullable=False),
        sa.Column('description', String, nullable=True),
        sa.Column('status', String, nullable=False),
        sa.Column('created_at', DateTime(timezone=True), server_default=func.now(), nullable=False),
        sa.Column('updated_at', DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False),
        sa.Column('created_by', BigInteger, nullable=False)
    )

    # Create the user_campaign_sequence table
    op.create_table(
        'user_campaign_sequence',
        sa.Column('id', BigInteger, primary_key=True, autoincrement=True),
        sa.Column('user_campaign_id', BigInteger, ForeignKey('user_campaign.id'), nullable=False),
        sa.Column('scheduled_date', DateTime(timezone=True), nullable=False),
        sa.Column('status', String, nullable=True),
        sa.Column('created_at', DateTime(timezone=True), server_default=func.now(), nullable=False),
        sa.Column('updated_at', DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False),
        sa.Column('created_by', BigInteger, nullable=False)
    )


def downgrade():
    # Drop the user_campaign_sequence table if we need to downgrade
    op.drop_table('user_campaign_sequence')

    # Drop the user_campaign table if we need to downgrade
    op.drop_table('user_campaign')
